site_name: Git Book
site_description: A book on how to use Git
site_author: Tatsuya Shiotsuka
site_url: https://SHIO777.github.io/git-book
repo_name: SHIO777/git-book
repo_url: https://github.com/SHIO777/git-book
edit_uri: ./edit/main/docs
copyright: Copyright &copy 2022 SHIO777

theme:
  name: material
  palette:
    scheme: preference
    primary: indigo
    accent: amber
  font:
    text: Noto Sans
    code: Inconsolata
  language: ja
  logo: img/git-logo.svg
  favicon: img/git-icon.svg
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - meta

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - ホーム: index.md
  - 1. Gitとは:
      - 1.1 Gitについて: ch01-01-about-git.md
      - 1.2 GitとGitHubの違い: ch01-02-git-and-github.md
  - 100. appendix:
      - 100.1 command memo: ch100-01-command.md
